### ISSUE TITLE
google-glog not a good installation directory name on Windows

### ISSUE THREAD

**Issue by bvanevery** [sergiud/glog#2]
Default installation is to C:\Program Files\google-glog .  Other projects however will likely use CMake's find_package command to try to locate Glog.  So it is probably best to refer to the package as Glog, so that it is installed in C:\Program Files\Glog , and searched for there as such.

**Comment by sergiud** [comment]
The installation path is unrelated to `find_package`. `CMakeLists.txt` already generates a config file which allows to locate glog by calling `find_package(glog)`.

**Comment by bvanevery** [comment]
But who is going to have this config file / why is it already going to be in place / how is it found?  When I ran an install, the only _.cmake files installed were into C:\Program Files\google-glog\lib\cmake\glog\_.cmake .  I see no reason why anyone's going to know those exist.  Ergo, name the project Glog so the installation directory is C:\Program Files\Glog so that other people's CMake scripts can find it without any effort.

**Comment by sergiud** [comment]
You are mixing several things. `google-glog` is just the project name consistent with current naming convention. If you are unhappy with the default installation path, you can always change it. The package itself is called `glog`. The config file is always part of the package. The user does not have to know where it is since CMake will automatically locate the config files in the sub-directory you mentioned previously. If CMake does not find the config file, you have to specify the (root) install path using `glog_DIR` CMake variable (in your case `C:\Program Files\google-glog`).

Also, since the `glog-config.cmake` is already part of the package, other people do not have to write their own find modules. You have to simply call `find_package(glog)` in your `CMakeLists.txt`.

You may want to read http://www.cmake.org/cmake/help/v3.0/command/find_package.html for more details on how `find_package` works.

**Comment by bvanevery** [comment]
I hope we agree that the user shouldn't _have_ to know how you did things, and things should just automatically work, as the default case.  Expecting the user to type glog_DIR manually is cheating.

Concrete example: I'm building ceres-solver on Windows 7.  It has its own CMake build system.  It's trying to find glog using its own FindGlog.cmake module.  It doesn't know anything about your code, your choice of installation directory names, or your config files.  None of that information is published anywhere that it would know to find.  It simply uses directory conventions to find stuff, same as most FindWhatever.cmake modules out there "in the wild".  It searches Unix style /usr/local/include directories for glog/logging.h and /usr/local/lib for glog.lib.  Of course on Windows these don't exist and frankly right now, their code gives up.  I'm trying to get them to fix their code.  I need to convince them that there's a standard place to look for glog.  The sane choice is C:\Program Files\Glog.  

When evaluating "sanity", it may be useful to look at how glog is actually used elsewhere.  The Ubuntu Launchpad package http://launchpadlibrarian.net/190390308/libgoogle-glog-dev_0.3.3-2build1_amd64.deb has the following directory structure:

/usr/include/glog
/usr/lib/x86_64-linux-gnu/libglog.a
/usr/lib/x86_64-linux-gnu/pkgconfig/libglog.pc
/usr/share/doc/libgoogle-glog-dev

Please note that Windows users don't care about Ubuntu packaging conventions such as libgoogle-glog-dev, as they aren't using that packaging system.  Nor are Linux package names stable in any event anyways: try comparing the names for similar software on different distros.  Anyways, Windows users care about the functional bits, the directories and libs, that are all simply going by the root word "glog".  Not "google-glog", there's no basis or precedence for that.  Even the Unix package config is simply using "glog", so there must be something to this.  ;-)

You can't count on people using your glog-config.cmake code, or any of your FindWhatever.cmake modules, in their own projects.  They might use your code, they might already have their own code.  They might borrow your code at some point, find there's a bug, roll their own version, and diverge from what you're doing.  That's what happens with most of the modules that ship with CMake, because the maintenance on them is pretty stale.

Especially since your code isn't a standard shipping component of glog, every piece of current SW that's trying to locate a glog doesn't know anything about how you're doing things.  As a final corner case, why do you even assume that some other project is using CMake as the build system and can use *.cmake modules?  That's why people put things in standard locations with standard names, so that other people can find them.

On Windows, this should be C:\Program Files\Glog\ .

**Comment by sergiud** [comment]
I still don't see your problem. If you don't like the default installation
path, you can change it. On Windows, the are no standard paths, so you must
amlost always specify them. It's not cheating, this is how CMake actually works.

I also use Ceres and had to patch their CMakeLists.txt which is mostly
broken anyway.

**Comment by sergiud** [comment]
Note also that glog already follows CMake/Unix conventions regarding the
directory structure. There are no changes needed.

The way you are trying to fix your problems with Ceres is pretty much
wrong. Especially enforcing the search prefix to be in C:\Program Files.
Not everyone uses this directory as install prefix. I don't. Instead, Ceres
must fix their code and use the config files provided by the libraries
without rolling out their own.

**Comment by bvanevery** [comment]
The standard path for installing things in Windows is %HOMEDRIVE%\Program Files.  Look for instance at where the Windows SDK is installed.  Just because it is not _quite_ as on the tip of everyone's tongue as /usr and /usr/local are in the Unix world, doesn't mean it isn't standard.  Especially WRT CMake.  I was battling for that kind of conventional behavior for CMake on Windows, with Kitware on their mailing list, as far back as 2006.

The user is not _forced_ to use C:\Program Files.  Just as a user is not _forced_ to use /usr/local on Unix.  It is just the place where things are expected to be, and if things aren't in the expected place, then the user can manually enter where their custom directory is.  Conventions exist so that _automatic_ behavior is possible.

The goal is to avoid the user having to enter anything.  To have the build just work, by leveraging the typical naming conventions on the platform.  That's why people write FindWhatever.cmake modules.  If the module isn't finding anything, when it jolly well could, then asking the user for manual input is cheating.  It is a PITA for users to figure out what's going on, and also for people trying to set up automated builds.  Things should just work, in a standard way, when they can.

I think the issue is you don't value these points of directory convention clarity the way I do.  You seem to think that the Windows platform is about "rolling your own".

**Comment by sergiud** [comment]
As I already said, using own find modules while the library itself already provides config files is not the way CMake is supposed to work. Providing `project-config.cmake` files is the preferred way. Please read the documentation. That's the reason I'm providing these files.

Also, `find_package` does not look in `C:\Program Files` for packages. As I see it, you need to hardcode the path in your find module.

If you use the provided files, you don't have to specify any paths anyway. CMake stores package paths in the user package registry. The package will therefore be found automatically. You may want to read http://www.cmake.org/cmake/help/v3.0/manual/cmake-packages.7.html#manual:cmake-packages(7) for more information.

**Comment by sergiud** [comment]
By the way, I strongly disagree that `%HOMEDRIVE%\Program Files` is a standard path for libraries. I could care less where Windows SDK is installed. Installing libraries in `%HOMEDRIVE%\Program Files` is your convention, but not mine.

**Comment by bvanevery** [comment]
You've told me several times to read the docs... as a courtesy, I've obliged several times... why do you believe the docs say anyone's gonna find a glog installed in google-glog?  The find_package() docs say these are the directories searched:

(Stupid Github is trying to interpret these chars, so I had to change them.)

_prefix_/                                               (W)
_prefix_/(cmake|CMake)/                                 (W)
_prefix_/_name__/                                       (W)
_prefix_/_name__/(cmake|CMake)/                         (W)
_prefix_/(lib/_arch_|lib|share)/cmake/_name__/          (U)
_prefix_/(lib/_arch_|lib|share)/_name__/                (U)
_prefix_/(lib/_arch_|lib|share)/_name_*/(cmake|CMake)/  (U)

When you install to google-glog instead of Glog, you're messing up the _name_.  People don't type find_package(google-glog), they type find_package(Glog).  When I keep talking about %HOMEDRIVE%\Program Files, I mean that's almost always the _prefix_ on a 64-bit Windows system.  Not that anyone needs to hardwire those exact words into their code.

Please also note those (W)s indicate _standard_ Windows directory conventions as far as CMake is concerned, regardless of how you personally feel about those conventions.

I don't mean to belittle your good work.  You've made a nice port and it almost works well, but it isn't a standard shipping component of glog, and it hasn't been vetted by lots of users.  Meanwhile, lots of other projects have evolved their own CMake builds and ways of trying to find include files and libs on Windows.  Looking in %HOMEDRIVE%\Program Files, aka CMAKE_INSTALL_PREFIX, is a very common strategy.  People aren't averse to hardwiring search directories either, whatever the platform, seeing as how \Program Files\ is just as common on Windows as /usr and /usr/local are on Unix.

Various CMake based projects do already try to find glog.  I suspect, however, that these projects have little experience on Windows.  glog itself provides a fairly old and broken .sln build as you well know.  I don't see any evidence of glog being a robust production reality on the Windows platform.  Probably these CMake-based projects got it working on Unix, got it working on OSX, and it may have worked on Windows once at some point.  Probably won't work again until someone more Windows oriented comes along and prods the project.

I'm currently prodding ceres-solver for instance, and yes they do have a C:\Program Files\Glog based search strategy working now.  They had these TODO notices in their *.cmake code about adding Windows search paths to go with the Unix search paths.  I just got them to do what they said they had a mind to do, once upon a time.  I didn't ask them to completely rewrite their code or think a lot about what they're doing.

Where the Windows SDK is installed by default, is not a matter of opinion, whether you care about it or not.  The default installation is %HOMEDRIVE%\Program Files (x86)\Microsoft SDKs\ , even on a 64-bit system.  I count 9 subdirectories and I don't have that many MS SDKs installed:

Cpp REST SDK for Visual Studio 2013
Expression
F#
Microsoft Azure
Portable
TypeScript
Windows
Windows Phone
WindowsPhoneApp

Please do what most of the rest of us are doing.  You can't count on people to use your _.cmake code.  You can't count on people to program a CMake Find_ module exactly how you'd do it.  You can't even count on people using CMake as the build system.  What if I want Premake or SCons and just see your CMake as a sane way to get Glog built and installed on Windows?  The only glue between such heterogeneous builds is the naming convention, and it should be %HOMEDRIVE%\Program Files\Glog on a 64-bit Windows system.

That is, if you think full automation based on conventions is worth something, and I do.

**Comment by sergiud** [comment]
Fixed in #152.
